<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Condition="'$(TargetFramework)' == 'net8.0'" Version="8.0.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Condition="'$(TargetFramework)' == 'net9.0'" Version="9.0.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Condition="'$(TargetFramework)' == 'net10.0'" Version="10.0.*" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PhenX.EntityFrameworkCore.BulkInsert.Tests" />
    <InternalsVisibleTo Include="PhenX.EntityFrameworkCore.BulkInsert.MySql" />
    <InternalsVisibleTo Include="PhenX.EntityFrameworkCore.BulkInsert.PostgreSql" />
    <InternalsVisibleTo Include="PhenX.EntityFrameworkCore.BulkInsert.SqlServer" />
    <InternalsVisibleTo Include="PhenX.EntityFrameworkCore.BulkInsert.Sqlite" />
  </ItemGroup>

</Project>
