<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <!-- Ignore error for preview version of Pomelo.EntityFrameworkCore.MySql -->
    <NoWarn>$(NoWarn);NU5104</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PhenX.EntityFrameworkCore.BulkInsert\PhenX.EntityFrameworkCore.BulkInsert.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NetTopologySuite" Version="2.6.0" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Condition="'$(TargetFramework)' == 'net8.0'" Version="8.0.*" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Condition="'$(TargetFramework)' == 'net9.0'" Version="9.0.0-preview.3.efcore.9.0.0" />
  </ItemGroup>

</Project>
